### PR TITLE
Fix for openshift clusters

### PR DESCRIPTION
**Pull request by bond-**
This is a fix for: https://github.com/reportportal/reportportal/issues/2075

Without this fix, we aren't able to update to report-portal 5.8.0. Please let me know if any other comments I will address them as soon as possible

Information on how to make this accessible for openshift: https://docs.okd.io/4.13/openshift_images/create-images.html#use-uid_create-images

### CODE REVIEW

**Comment by bond-** [comment]
Sorry for the typo in the feature branch name, not intentional.

**Comment by bond-** [comment]
@HardNorth good to merge?

**Comment by raikbitters** [comment]
@bond- Hello. Thanks for the improvement. Works well. 
DockerfileDev will be deleted because It's legacy. You can use the main Dockerfile for testing development.

**Comment by bond-** [comment]
@raikbitters Can a new release be made, we sort of need this fix in our corp deployment?

**Pull request merged**
